Download classic runtime by default
AppImage/appimagetool pull request #33
Opened 2023-07-16 13:26 UTC by TheAssassin

The static runtime is still considered experimental and not nearly as battle-tested as the "classic" variant from AppImageKit.

For users who wish to download the static variant instead, an environment variable was added which changes the new default behavior.

This commit allows me to use this new appimagetool in linuxdeploy-plugin-appimage, which would serve as a field test for the tool itself. I do not want to make people use the static variant until it is fully compatible with everything and the specification changes have been made.

2023-07-16 22:12 UTC, probonopd commented
Let's change it the other way around - static by default, old by opt-in.
This would be in line with https://github.com/AppImage/AppImageKit/issues/877#issuecomment-1588584063 - which got lots of upvotes.

The old runtime is not maintained anymore, not recommended anymore.

2023-07-16 22:13 UTC, probonopd requested changes
Please make the old runtime opt-in. After all, who does nothing still gets the old runtime from the AppImageKit repo. People who change to this repo do so because they want the static runtime.

2023-07-16 22:13 UTC, TheAssassin commented
Nope. I explained the rationale very well. The vast majority of AppImages is built with regular appimagetool. This tool can't just switch to some experiment without prior notice.

It was you who wanted to have no unnecessary changes before a 1.0 release.

2023-07-16 22:14 UTC, TheAssassin commented
> People who change to this repo do so because they want the static runtime.

Show me. This repository has not been advertised anywhere on purpose. At least not by me. Which is in line with what we discussed recently.

2023-07-16 22:14 UTC, probonopd commented
appimagetool is free to use the old appimagetool or opt out of the static runtime. Although I thought we wanted to get rid of the old dynamically linked runtime asap.

2023-07-16 22:15 UTC, probonopd commented
> Show me. 

See the upvotes on https://github.com/AppImage/AppImageKit/issues/877#issuecomment-1588584063 - people can't wait to get the static runtime due to Ubuntu not shipping libfuse2 anymore.

2023-07-16 22:16 UTC, TheAssassin commented
> The old runtime is not maintained anymore, not recommended anymore.

It is of course still maintained actively, being part of the core AppImage repositories. Just because there are no changes doesn't mean that it is not maintained. Please stop spreading misleading information.

> upvotes

are not a representative statistic measure in anyway. Just looking at the download counts proves you wrong.

2023-07-16 22:45 UTC, probonopd commented
Well. For me, using the soon-to-be deprecated dynamic runtime in the new appimagetool by default kinda defeats the purpose and unneccessarily makes it complex for people to finally switch the the static runtime, which they have been awaiting ever since Ubuntu no longer shipped libfuse2 by default.

2023-10-28 09:55 UTC, probonopd commented
@TheAssassin have you found a way to update AIL so that this PR is no longer needed?

2024-12-03 20:06 UTC, TheAssassin commented
Yes, let's close it. I hope to make a prerelease of AIL this week.

2024-12-03 20:06 UTC, closed without merging